version: 2.1

# jobs:
  # build:
  #   working_directory: ~/Employees
  #   docker:
  #     - image: circleci/node:latest  
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install dependencies
  #         command: npm install
  #     - run:
  #         name: Run tests
  #         command: npm test
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - build

jobs:
  build:
    working_directory: ~/Employees
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@5
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-app-web
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USER@$AWS_EC2_PUBLIC_DNS "
            export SERVER='$SERVER';
            export PRIVATE_KEY='$PRIVATE_KEY';
            rm -rf DevOpsCa/;
            git clone https://github.com/janekeyes/CA2.git;
            cd DevOpsCa;
            chmod +x deploy.sh && bash deploy.sh"
