version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - build

jobs:
  build:
    working_directory: ~/CA2
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
         name: Start Rails Server
         command: bundle exec rails server -b 0.0.0.0 -p 3000

      - run:
          name: Update npm
          command: sudo npm install -g npm@5

      - run:
          name: Install Dependencies
          command: npm cache clean --force && npm install
      - run:
          name: Debug File Permissions
          command: 
           ls -l bin
           file bin/brakeman
      
      - run:
    name: Grant execute permission for brakeman
    command: chmod +x bin/brakeman


  -save cache:
      key: dependency-cache-{{ checksum "package-lock.json" }}
      paths: 
      - ./node_modules

  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$AWS_EC2_PUBLIC_DNS "
              export SERVER='$SERVER';
              export PRIVATE_KEY='$PRIVATE_KEY';
              rm -rf CA2/;
              git clone https://github.com/janekeyes/CA2.git;
              cd CA2;
              chmod +x deploy.sh && bash deploy.sh"
